# Generated by Django 5.1.5 on 2025-01-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial1App', '0002_part_delete_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='numberOfArgs',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='part',
            name='arg0Name',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='part',
            name='arg0Value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='part',
            name='arg1Name',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='part',
            name='arg2Name',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='part',
            name='arg2Value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='part',
            name='arg3Name',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='part',
            name='arg3Value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='part',
            name='arg4Name',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='part',
            name='arg4Value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='part',
            name='arg5Name',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='part',
            name='arg5Value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='part',
            name='arg6Name',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='part',
            name='arg6Value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='part',
            name='arg7Name',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='part',
            name='arg7Value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='part',
            name='arg8Name',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='part',
            name='arg8Value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='part',
            name='functionName',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
