# Generated by Django 5.1.5 on 2025-01-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial1App', '0003_part_numberofargs_alter_part_arg0name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='check_in',
            new_name='checkin',
        ),
    ]
