# Generated by Django 5.1.5 on 2025-01-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial1App', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='numberOfArgs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='part',
            name='numberOfArgs',
            field=models.IntegerField(default=0),
        ),
    ]
