# Generated by Django 5.1.5 on 2025-01-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial1App', '0006_alter_order_numberofargs_alter_part_numberofargs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkin',
            field=models.BooleanField(null=True),
        ),
    ]
