# Generated by Django 5.1.5 on 2025-01-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial1App', '0007_alter_order_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkin',
            field=models.BooleanField(default=False),
        ),
    ]
