# Generated by Django 5.1.5 on 2025-01-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial1App', '0008_alter_order_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='checkin',
            field=models.BooleanField(default=False),
        ),
    ]
