# Generated by Django 5.1.5 on 2025-01-27 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial1App', '0009_alter_part_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='part',
            name='functionName',
        ),
    ]
