# Generated by Django 5.1.5 on 2025-01-27 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_companyinfo_address'),
        ('trial1App', '0011_part_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='user',
        ),
        migrations.AddField(
            model_name='part',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.companyinfo'),
            preserve_default=False,
        ),
    ]
