# Generated by Django 5.1.5 on 2025-01-29 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_companyinfo_address'),
        ('trial1App', '0012_remove_part_user_part_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='arg0Name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='arg1Name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='arg2Name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='arg3Name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='arg4Name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='arg5Name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='arg6Name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='arg7Name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='arg8Name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='order',
            name='numberOfArgs',
        ),
        migrations.RemoveField(
            model_name='order',
            name='partName',
        ),
        migrations.RemoveField(
            model_name='order',
            name='templateName',
        ),
        migrations.RemoveField(
            model_name='order',
            name='userName',
        ),
        migrations.AddField(
            model_name='order',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trial1App.part'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.companyinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
