# Generated by Django 5.1.5 on 2025-01-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usertype_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='user',
        ),
    ]
