# Generated by Django 5.1.5 on 2025-01-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_companyname_companyinfo_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='company',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='contact',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
