# Generated by Django 5.1.5 on 2025-01-29 04:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_companyinfo_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerInfo',
            new_name='UserInfo',
        ),
    ]
